# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Install dependencies
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      # Build the book
      - name: Build the book
        run: |
          jupyter-book build .

      # Create github-pages artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          # Path of the directory containing the static assets.
          path: ./_build/html

      # Deploy artifact
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3
